### ISSUE TITLE
Compatibility issue with Community Patch "AntiJank"

### ISSUE THREAD

**Issue by Urijahuri** [tstavrianos/BannerLordLauncher#3]
the latest prerelease of the Community patch has included an Anti-jank extension for the launcher that causes a "mscorlib" crash when used with this mod.

error/stacktrace:
```
System.Reflection.ReflectionTypeLoadException
HResult=0x80131602
Nachricht = Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
Quelle = mscorlib
Stapelüberwachung:
at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
at System.Reflection.Assembly.GetTypes()
at TaleWorlds.MountAndBlade.Module.CollectModuleAssemblyTypes(Assembly moduleAssembly)
at TaleWorlds.MountAndBlade.Module.LoadSubModules()
at TaleWorlds.MountAndBlade.Module.Initialize()
```

Release: https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/releases/tag/0.1.0-rc2

**Comment by Cebullus** [comment]
https://github.com/Tyler-IN/MnB2-Bannerlord-CommunityPatch/issues/240
There is a fix in internal testing of Community Patch 0.1.0-rc3
